/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#4723be',
        'tertiary': '#000000',
        'secondary': '#5d5f5f',
        'on-background': '#1c1b1b',
        'primary-fixed-dim': '#c8c6c5',
        'on-surface-variant': '#444748',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#313030',
        'on-secondary-fixed': '#1a1c1c',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#cabeff',
        'primary': '#000000',
        'on-primary': '#ffffff',
        'background': '#fcf9f8',
        'tertiary-container': '#1c0062',
        'secondary-container': '#dfe0e0',
        'surface-tint': '#5f5e5e',
        'outline-variant': '#c4c7c7',
        'primary-fixed': '#e5e2e1',
        'on-secondary-container': '#616363',
        'surface-variant': '#e5e2e1',
        'on-tertiary': '#ffffff',
        'on-surface': '#1c1b1b',
        'outline': '#747878',
        'inverse-on-surface': '#f3f0ef',
        'secondary-fixed': '#e2e2e2',
        'surface-container': '#f0edec',
        'on-error-container': '#93000a',
        'on-primary-container': '#858383',
        'on-secondary-fixed-variant': '#454747',
        'on-tertiary-container': '#866cfe',
        'on-primary-fixed-variant': '#474646',
        'secondary-fixed-dim': '#c6c6c7',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'inverse-primary': '#c8c6c5',
        'surface': '#fcf9f8',
        'surface-container-low': '#f6f3f2',
        'on-primary-fixed': '#1c1b1b',
        'surface-container-highest': '#e5e2e1',
        'on-secondary': '#ffffff',
        'primary-container': '#1c1b1b',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#e6deff',
        'surface-container-high': '#ebe7e7',
        'on-tertiary-fixed': '#1c0062',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}